version: "3.8"

services:
  #MySQL Database
  mariadb-green:
    image: mariadb:latest
    container_name: d2c-mariadb-green
    restart: unless-stopped
    environment:
      MARIADB_BLUE_ROOT_PASSWORD: ${MARIADB_GREEN_ROOT_PASSWORD}
      MARIADB_BLUE_DATABASE: ${MARIADB_GREEN_DATABASE:-d2c_fashion}
      MARIADB_BLUE_USER: ${MARIADB_GREEN_USER}
      MARIADB_BLUE_PASSWORD: ${MARIADB_GREEN_PASSWORD}
      MARIADB_BLUE_CHARSET: utf8mb4
      MARIADB_BLUE_COLLATION: utf8mb4_unicode_ci
    ports:
      - "${MARIADB_GREEN_PORT:-3307}:3306"  
    volumes:
      - green-mariadb_data:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d
    healthcheck:
      #test: ["CMD","mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 10s
      timeout: 10s 
      retries: 10
      start_period: 120s
    networks:
      - app-network
    command:
      - --max_connections=1000
      - --wait_timeout=600
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  
  # FastAPI Backend
  backend-green:
    image: ghcr.io/swapnil-lakra/deploy-sheild/fastapi-backend:latest
    container_name: d2c-backend-green 
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql+aiomysql://${MARIADB_GREEN_USER}:${MARIADB_GREEN_PASSWORD}@mysql:3306/d2c_fashion?charset=utf8mb4
    ports:
      - "8001:8000"
    depends_on:
      mariadb-green:
        condition: service_healthy
    networks:
      - app-network
  
  #Next.js Frontend
  frontend-green:
    image: ghcr.io/swapnil-lakra/deploy-sheild/nextjs-frontend:latest
    container_name: d2c-frontend-green
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000
    ports:
      - "3001:3000"
    depends_on:
      backend-green:
        condition: service_started
    networks:
      - app-network

volumes:
  green-mariadb_data:

networks:
  app-network:  
    driver: bridge
  
   