server { 
    listen 80;
    server_name _;

    # Frontend upstream
    upstream frontend {
        server 127.0.0.1:3000 weight=10;
        server 127.0.0.1:3001 weight=0;
    }

    # Backend upstream
    upstream backend {
        server 127.0.0.1:8000 weight=10;
        server 127.0.0.1:8001 weight=0;
    }

    # Health Check
    location /health {
        default_type application/json;
        return 200 '{
            "status": "healthy",
            "active_environment": "blue"
        }';
    }

    # Frontend
    location / {
        proxy_pass http://frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Backend
    location /api/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}