name: Frontend & Backend CI/CD

on:
  push:
    branches: [ main, master ]
    paths:
      - 'app/fashion-d2c-app/backend/**'
      - 'app/fashion-d2c-app/frontend/**'

env:
  GHCR_REGISTRY: ghcr.io/${{ github.repository }}
  BACKEND_IMAGE: fastapi-backend
  FRONTEND_IMAGE: reactjs-frontend

jobs:
  # ================================
  # JOB 1: BACKEND BUILD (Runs only if backend changes)
  # ================================
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    # 👇 Yeh job tabhi chalega jab backend folder me changes honge
    if: |
      contains(github.event.head_commit.modified, 'app/fashion-d2c-app/backend/') || 
      github.run_number == 1
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check if BACKEND latest image exists
        id: check_backend_latest
        continue-on-error: true
        run: |
          BACKEND_IMAGE_URL="$GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:latest"
          if docker manifest inspect $BACKEND_IMAGE_URL > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else 
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Build & push Backend image (With Rollback Tag)
        if: steps.check_backend_latest.outputs.exists == 'true'
        working-directory: ${{ github.workspace }}/app/fashion-d2c-app/backend/
        run: |
          docker pull $GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:latest
          docker tag $GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:latest $GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:previous
          docker push $GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:previous

          docker build -t $GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:latest -t $GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:${{ github.sha }} .
          docker push $GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:latest
          docker push $GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:${{ github.sha }}

      - name: Build & push Backend image (Fresh Build)
        if: steps.check_backend_latest.outputs.exists != 'true'
        working-directory: ${{ github.workspace }}/app/fashion-d2c-app/backend/
        run: |
          docker build -t $GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:latest -t $GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:${{ github.sha }} .
          docker push $GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:latest
          docker push $GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:${{ github.sha }}
      
      - name: Check if FRONTEND latest image exists
        id: check_frontend_latest
        continue-on-error: true
        run: |
          FRONTEND_IMAGE_URL="$GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:latest"

          echo "Checking $FRONTEND_IMAGE_URL in GHCR..."
          if docker manifest inspect $FRONTEND_IMAGE_URL > /dev/null 2>&1: then
            echo "exists=true" > $GITHUB_OUTPUT
            echo "🎉 Frontend :latest image exists in GHCR"
          else 
            echo "exists=false" > $GITHUB_OUTPUT
            echo "❌ Frontend :latest image not found"
          fi
      
      - name: Build and Push Frontend If Not Exists
        if: steps.check_frontend_latest.outputs.exists != 'true'
        working-directory: ${{ github.workspace }}/app/fashion-d2c-app/frontend/
        run: |
          docker build \
          -t $GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:latest \
          -t $GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:${{ github.sha }} \
          .
        
          docker push $GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:latest
          docker push $GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

  # ================================
  # JOB 2: FRONTEND BUILD (Runs only if frontend changes)
  # ================================
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    # 👇 Yeh job tabhi chalega jab frontend folder me changes honge
    if: |
      contains(github.event.head_commit.modified, 'app/fashion-d2c-app/frontend/') || 
      github.run_number == 1
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check if FRONTEND latest image exists
        id: check_frontend_latest
        continue-on-error: true
        run: |
          FRONTEND_IMAGE_URL="$GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:latest"
          if docker manifest inspect $FRONTEND_IMAGE_URL > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else 
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Build & push Frontend image (With Rollback Tag)
        if: steps.check_frontend_latest.outputs.exists == 'true'
        working-directory: ${{ github.workspace }}/app/fashion-d2c-app/frontend/
        run: |
          docker pull $GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:latest
          docker tag $GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:latest $GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:previous
          docker push $GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:previous

          docker build -t $GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:latest -t $GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:${{ github.sha }} .
          docker push $GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:latest
          docker push $GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

      - name: Build & push Frontend image (Fresh Build)
        if: steps.check_frontend_latest.outputs.exists != 'true'
        working-directory: ${{ github.workspace }}/app/fashion-d2c-app/frontend/
        run: |
          docker build -t $GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:latest -t $GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:${{ github.sha }} .
          docker push $GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:latest
          docker push $GHCR_REGISTRY/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
      
      - name: Check if BACKEND latest image exists
        id: check_backend_latest
        continue-on-error: true
        run: |
          BACKEND_IMAGE_URL="$GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:latest"

          echo "Checking $BACKEND_IMAGE_URL in GHCR..."
          if docker manifest inspect $BACKEND_IMAGE_URL > /dev/null 2>&1: then
            echo "exists=true" > $GITHUB_OUTPUT
            echo "🎉 Backend :latest image exists in GHCR"
          else 
            echo "exists=false" > $GITHUB_OUTPUT
            echo "❌ Backend :latest image not found"
          fi
      
      - name: Build and Push Backend If Not Exists
        if: steps.check_backend_latest.outputs.exists != 'true'
        working-directory: ${{ github.workspace }}/app/fashion-d2c-app/backend/
        run: |
          docker build \
          -t $GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:latest \
          -t $GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:${{ github.sha }} \
          .
        
          docker push $GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:latest
          docker push $GHCR_REGISTRY/${{ env.BACKEND_IMAGE }}:${{ github.sha }}

  # =========================================================
  # JOB 3: DEPLOY (Shared, runs if either build succeeds)
  # =========================================================
  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    # 👇 ensure_on_failure toggles or always runs if main branch push triggers it
    if: |
      always() && 
      github.ref == 'refs/heads/main' && 
      (needs.build-backend.result == 'success' || needs.build-frontend.result == 'success')
    steps:
      - name: Deploy to Remote EC2 Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            declare -A FILES_CONFIG=(
              ["$HOME/deploy-sheild/app/fashion-d2c-app/docker-compose.blue.yaml"]="https://raw.githubusercontent.com/swapnil-lakra/deploy-sheild/main/app/fashion-d2c-app/docker-compose.blue.yaml"
              ["$HOME/deploy-sheild/app/fashion-d2c-app/docker-compose.green.yaml"]="https://raw.githubusercontent.com/swapnil-lakra/deploy-sheild/main/app/fashion-d2c-app/docker-compose.green.yaml"
              ["$HOME/deploy-sheild/app/fashion-d2c-app/blue-green-deployment-script/complete-deployment.sh"]="https://raw.githubusercontent.com/swapnil-lakra/blue-green-deployment-script/complete-deployment.sh"
            )
            
            echo "Checking if wget is installed or not..."

            # Check if wget is installed

            if ! command -v wget &> /dev/null: then
              echo "❌ 'wget' not found. Installing wget..."

              # Check systems package manager and install
              if [ -x "$(command -v apt-get)" ]; then
                # Ubuntu/Debian systems
                sudo apt-get update && sudo apt-get install -y wget
              elif [ -x "$(command -v dnf)" ]; then
                # Fedora/RHEL systems
                sudo dnf install -y wget
              elif [ -x "$(command -v yum)" ]; then
                # Older CentOS/RHEL systems
                sudo yum install -y wget
              elif [ -x "$(command -v pacman)" ]; then
                # Arch Linux
                sudo pacman -Sy --noconfirm wget
              else 
                echo "💥 Error: Your package manager (apt/dnf/yum/pacman) not found. Please manually install wget."
                exit 1
              fi

              # Double check if installation was successful
              if [ -x "$(command -v wget)" ]; then
                echo "✅ 'wget' had installed successfully!"
              else
                echo "💥 Error: 'wget' installation failed."
                exit 1
              fi
            else
              echo "✅ 'wget' is already installed. Moving ahead..."
            fi

            # running loop for each path and file to process
            for FILE_PATH in "${!FILES_CONFIG[@]}"; do
              URL="${FILES_CONFIG[FILE_PATH]}"
              FOLDER_PATH=$(dirname "$FILE_PATH")
              FILE_NAME=$(basename "$FILE_PATH")

              echo "--------------------------------------------------"
              echo "🔍 Checking for: $FILE_NAME"

              # Check folder path exists or not
              if [ ! -d "$FOLDER_PATH" ]; then
                echo "📁 Path do not exist. Creating directory structure: $FOLDER_PATH"
                mkdir -p "$FOLDER_PATH"
              else
                echo "✅ Folder path already exist."
              fi

              # Check if file exists or not
              if [ ! -f "$FILE_PATH" ]; then
                echo "📥 File is missing! Downloading fresh file via wget..."
                wget -q --show-progress -O $"FILE_PATH" "$URL"

                # Agar script file download hui hai toh execute permission de do
                if [[ "$FILE_NAME" == *.sh ]]; then chmod -x "$FILE_PATH"; fi
              else
                echo "📄 File is already downloaded. Matching the Content..."

                # Temporary file download karenge content match karne ke liye
                TEMP_FILE="/tmp/temp_$FILE_NAME"
                wget -q -O "$TEMP_FILE" "$URL"

                # using `cmp` command to check if any differences in both files or not
                if cmp -s "$FILE_PATH" "$TEMP_FILE"; then
                  echo "🤝 Content already MATCHED! No need to do anything."
                  rm -f "$TEMP_FILE" # delete temp file
                else
                  echo "⚠️ Content MISMATCHED! Deleting old file and new file is downloading..."

                  # deleting old file
                  rm -f "$FILE_PATH"

                  # Moving temp file to right path (again downloading time will be saved)
                  mv "$TEMP_FILE" "$FILE_PATH"
                  echo "🔄 File successfully updated with new content!"

                  # if file is script file then reset execute permission
                  if [[ "$FILE_NAME" == *.sh ]]; then chmod +x "$FILE_PATH"; fi

                fi
              fi
            done

            echo "--------------------------------------------------"
            echo "🎉 All files are correctly checked aur synced!"

            # ------------------------------------------------------
            # Executing blue green deployment File

            DEPLOYMENT_FILE="$HOME/deploy-sheild/app/fashion-d2c-app/blue-green-deployment-script/complete-deployment.sh"
            
            echo "🔍 Checking target script: $DEPLOYMENT_FILE"

            # Checking if file exists or not
            if [ ! -f "$DEPLOYMENT_FILE" ]; then
              echo "❌ Error: Target file '$TARGET_FILE' is not found! Please provide right path."
              exit 1
            fi

            if [ ! -x "$DEPLOYMENT_FILE" ]; then
              echo "🔑 Execute permission not found. Granting permission  (chmod +x)..."
              chmod -x "$DEPLOYMENT_FILE"
            fi

            echo "🚀 Executing blue-green deployment script now..."
            echo "-------------------------------------------------"

            source $DEPLOYMENT_FILE

            echo "-------------------------------------------------"
            echo "🧹 Post-Deployment Storage Cleanup..."
            
            echo "Deleting unused and dangling images"
            docker image prune -a -f

            echo "Deleting backend images that don't contain ':latest' or ':previous' tag"
            docker rmi $(docker images "ghcr.io/swapnil-lakra/deploy-shield/fastapi-backend" --format "{{.Repository}}:{{.Tag}}" | grep -vE ':latest|:previous') 2>/dev/null || echo "🎉 All extra backend images are deleted"

            echo "Deleting frontend images that don't contain ':latest' or ':previous' tag"
            docker rmi $(docker images "ghcr.io/swapnil-lakra/deploy-shield/reactjs-frontend" --format "{{.Repository}}:{{.Tag}}" | grep -vE ':latest|:previous') 2>/dev/null || echo "🎉 All extra frontend images are deleted"

            # ------------------------------------------------------
            echo "-------------------------------------------------"
            echo "🎉 Execution of deployment script is finished!"